stages:
  - build_ci
  - ci
  - publish

variables:
  COMPOSER_COMMAND: "composer update --with=typo3/cms-core:dev-master"
  IMAGE: "$CI_REGISTRY/waldhacker/mainframe/docker/base/php/7.4:cli"

image: $IMAGE

build-dev:
  stage: build_ci
  tags:
    - common
  needs: []
  script:
    - composer self-update --preview
    - $COMPOSER_COMMAND
  artifacts:
    name: TYPO3
    paths:
      - .build/
      - ./composer.lock
    expire_in: '1h'

master-73:
  stage: ci
  needs: [ ]
  trigger:
    include: build/gitlab/master-73.yml
    strategy: depend

master-74:
  stage: ci
  needs: [ ]
  trigger:
    include: build/gitlab/master-74.yml
    strategy: depend

t310-74:
  stage: ci
  needs: [ ]
  trigger:
    include: build/gitlab/t310-74.yml
    strategy: depend

lint:
  stage: ci
  tags:
    - common
  needs:
    - build-dev
  script:
    - composer run ci:lint:yaml
    - composer run ci:lint:typoscript

psalm:
  stage: ci
  tags:
    - common
  needs:
    - build-dev
  script:
    - php -v
    - composer run ci:psalm

coverage:
  stage: ci
  tags:
    - common
  needs:
    - build-dev
  script:
    - composer run ci:tests:unit:cover
  artifacts:
    reports:
      cobertura: .build/logs/cobertura.xml


publish_tags:
  stage: publish
  tags:
    - common
  image: $CI_REGISTRY/waldhacker/mainframe/gitlab/runner/images/docker:stable
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+/'
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "https://$CI_SERVER_HOST/api/v4/projects/$CI_PROJECT_ID/packages/composer"'

publish_branch:
  stage: publish
  tags:
    - common
  image: $CI_REGISTRY/waldhacker/mainframe/gitlab/runner/images/docker:stable
  rules:
    - if: '$CI_COMMIT_TAG == null'
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data branch=$CI_COMMIT_BRANCH "https://$CI_SERVER_HOST/api/v4/projects/$CI_PROJECT_ID/packages/composer"'
